[package]
name = "diskplan"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
regex = "1"
nom = "7"
