[package]
name = "diskplan"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
regex = "1"
nom = "7"
nix = "0.23"
users = "0.11"
