[package]
name = "diskplan-filesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
camino.workspace = true
log.workspace = true
nix.workspace = true
users.workspace = true
